[project]
name = "ugram"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "pydantic-settings",
    "pydantic[email]",
    "email-validator",
    "psycopg2-binary",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
